### ISSUE TITLE
Dark/Dim conditions don't fall off properly

### ISSUE THREAD

**Issue by Eligarf** [Frstrm/TokenLightCondition#10]
![CPT2301041037-617x270](https://user-images.githubusercontent.com/16523503/210626083-1025a6de-6775-437d-996b-361d1e7308a1.gif)

Dim is still set when token is in dark, then dark doesn't fall off when token returns to dim. Both fall off when it steps back in bright. I checked the actor to make sure it wasn't a lagging badge on the token, and the effects were present when they shouldn't have been. The visibility check did the right thing though. I see the '-dim' text for entering dark, but the effect isn't actually gone....

**Comment by Frstrm** [comment]
Have been unable to repro locally.  Have added some armor around the clearEffects function.  Will continue to poke at it.
