### ISSUE TITLE
Compatibility warning "system" => "relationships.systems"

### ISSUE THREAD

**Issue by ZhornLegacy** [Frstrm/TokenLightCondition#13]
yay for v10 depreciation warnings
![image](https://user-images.githubusercontent.com/106674701/210946273-c426fcc0-4755-499a-98c8-232b5bd03a32.png)
![image](https://user-images.githubusercontent.com/106674701/210946301-acf79fc8-b1ae-486c-a4a2-2d4f8ec1d9ef.png)

**Comment by Frstrm** [comment]
huh, I'll take a look.  Haven't seen that in any of my logs.  Thanks.
