### ISSUE TITLE
Feature Request: Map-Based Display in Addition to Token Display

### ISSUE THREAD

**Issue by Dumbhuman** [Frstrm/TokenLightCondition#16]
First off, thank you for what you've already put into this!  The light affecting a character/monster is very useful information for many game features, but it can often be hard to distinguish visually (especially for players).

A potential added feature I'd love to see would be a way to perhaps press a key and get information for each visible grid square's current lighting.  That could be very helpful for things like Way of the Shadow Monks planning out teleports, Twilight Domain Clerics planning out flight paths, Shadow Dragons planning world domination, etc.

**Comment by Frstrm** [comment]
Thanks.  Unfortunately ( or fortunately depending point of view ) I'm not currently calculating each square of the canvas.  Just the tokens being placed.  Perfect Vision module has an overlay that you can key enable/disable to get that kind of quick overall information of the entire canvas.  I don't know if it's GM only or not.  default key for it is Ctrl+H I think.

**Comment by Dumbhuman** [comment]
Ah, I wasn't aware of that functionality in Perfect Vision, but it does seem to be GM only.

I understand that my request is probably outside the scope of your module (it's TokenLightCondition, not MapLightCondition after all), but I got excited and figured I'd ask just in case.  Your module at least lets me tell players they can use their token to test various grid squares of interest.
