### ISSUE TITLE
Support for CE broken, doesn't import the Dark condition

### ISSUE THREAD

**Issue by apoapostolov** [Frstrm/TokenLightCondition#25]
Only the Dim condition is being imported 
![image](https://user-images.githubusercontent.com/4083812/214978549-4d63fd0b-cd1e-4701-9bb0-8a9e9686da29.png)

This causes constant errors when using CE integration, which is needed to configure effects.
![image](https://user-images.githubusercontent.com/4083812/214978673-b01dfa1e-ba69-46f8-a5fa-b33fddc581f1.png)

![image](https://user-images.githubusercontent.com/4083812/214978765-2e5fabc9-09c7-4be1-87e8-0a02c9eef70d.png)

**Comment by Frstrm** [comment]
I'll take a look and see if I can run it down.
A local workaround is to go ahead and manually create a Dark CE effect for use.

**Comment by Frstrm** [comment]
I found a case where if you switch from any of the other methods to CE in settings, it doesn't create the CE effects until next reload.  I can fix that case up.  However, I'm not currently seeing where it would create one but not both.  I'll keep poking at it.
If you have any other details about how you ran into this state ( loading, changing settings, etc. F12 log errors ) it could help.

**Comment by apoapostolov** [comment]
Hello, it took a while (a reload or two) but the effects were created, it's probably best to include a popup asking to reload the environment when the errror happens so people try that and fix the issue via reload workaround. Unfortunately now that this is fixed, I cannot provide error messages.

**Comment by Frstrm** [comment]
After this change, it should attempt to create the CE effects as soon as you save the change to select CE as the effect Source in settings.
