### ISSUE TITLE
Option to turn off chat messages

### ISSUE THREAD

**Issue by apoapostolov** [Frstrm/TokenLightCondition#27]
I use my own way to visually emphasize on effect switching - I have commissioned a while ago a mod called Scrolling Texts that improves the visual design of the scrollable labels with 16-bit RPG style similar to old Combat Numbers mod, so the chat spam is not really useful for me. An option to turn it off would greatly decrease the cases where light causes me to scroll up and down for dice rolls, etc.

**Comment by Frstrm** [comment]
Can you screenshot an example?  This module doesn't in itself create any chat message.  I suspect your seeing CE or some other module indicating effect changes on tokens.

**Comment by apoapostolov** [comment]
Yes, it is likely CE. Is there a way to turn those off?

**Comment by Frstrm** [comment]
I believe within DFreds Convenient Effects settings, at the top, is 'Chat Message Permission'.  I believe setting that to 'None' turns off all chat messages.
