### ISSUE TITLE
Option to delay update of condition by miliseconds

### ISSUE THREAD

**Issue by apoapostolov** [Frstrm/TokenLightCondition#30]
This has been an issue with PF2 Darkness Effects during development - when players use keyboard to move their tokens around, they could cause multiple changes of condition and evenw ith TLC a slight delay can be felt when conditions change and scrolling text plays, when turned on.

A solution we came by was to add a customizable delay after the last movement of the token. When set to a value in milliseconds, say 1000 by default), the condition will not update until the player has stopped moving using keyboard.

**Comment by Frstrm** [comment]
Updated with 0.6.4
