### ISSUE TITLE
Option to apply global Dim condition

### ISSUE THREAD

**Issue by apoapostolov** [Frstrm/TokenLightCondition#31]
Related to #33 partially.

For scenes where the DM wants to have Twilight, an option in Settings that sets a Dim Light Threshold (default .60).

If the Scene Darkness is between global Dim Light Threshold and scene's Darkness Threshold, Bright Light by Global Illumination is considered Dim light not Bright Light. Bright Light from Light sources is treated as normal.

**Comment by Frstrm** [comment]
Perfect vision module allows you to set if the global Illumination is considered Bright or Dim.
Modifying global illumination and its settings are outside the scope of this module.
