### ISSUE TITLE
Functionality to use Negative Luminance Lights for Coverage and Magical Light

### ISSUE THREAD

**Issue by apoapostolov** [Frstrm/TokenLightCondition#32]
If a token is in Light with Negative Luminance (casting darkness instead of light) I am suggesting the following uses that allow to simulate fogs and magical darkness:

If a token is in Bright Light of a Light with Negative Luminance < 0, it is always in Darkness  even if the scene is bright ligth via Global Illumimation, or other light sources are cast on it. 

If a token is in Dim Light of a Light with Negative Luminance < 0, it is always in Dim Light even if the scene is bright ligth via Global Illumimation.

**Comment by Frstrm** [comment]
Updated with 0.6.4
