### ISSUE TITLE
Support for Landing Pages

### ISSUE THREAD

**Issue by apoapostolov** [Frstrm/TokenLightCondition#33]
If the active scene has Token Vision turned off, remove the Light conditions. 
If the active scene has Token Vision turned on, and also has Global Illumination turned on, consider Tokens in Bright Light.

**Comment by Frstrm** [comment]
I'm actively working to get Global Illumination working as a factor in determining token lighting conditions.
Scene token vision option has no impact on determining lighting conditions, only on token visibility.  ( i.e. walls still occlude lights, etc. )
I have already provided a method for disabling effects via lighting control options.
