### ISSUE TITLE
Enhancement: Global Illumination and Light Source Priority

### ISSUE THREAD

**Issue by schmickers** [Frstrm/TokenLightCondition#37]
Currently when the experimental option to use global illumination to determine token lighting is enabled, if the global illumination is set to bright light, and an area of negative luminance with a high priority is active on the canvas, tokens within this area still register as being illuminated by bright light. 

I would likle to suggest that lighting objects on the canvas with a priority set be compared against the global illumination, assigning the global illumination level a priority of 0.

This enables magical darkness or low light effects to function as intended.

**Comment by Frstrm** [comment]
can you screen shot an image of the settings/values your using so I can replicate/test against?  Thanks, I'll take a look at this.  I have seen other requests regarding using negative values for illumination.

**Comment by Frstrm** [comment]
Updated with 0.6.4
This should be covered by this change, but if not, let me know.
