### ISSUE TITLE
Enhancement: Darkvision

### ISSUE THREAD

**Issue by djohnsonnz** [Frstrm/TokenLightCondition#40]
Is it possible for an optional feature that allows creatures with darkvision to have dim light treated as normal light and darkness treated as dim light?

**Comment by Frstrm** [comment]
Unfortunately, that is outside the scope of this module.  That requires doing checks on tokens based on the token selected and it's various token settings, character feats, etc.  This modules intent is just to provide what is the lighting condition a token is in, and not how it is perceived by other tokens.

Might want to look at something like [Adequate Vision](https://github.com/stwlam/adequate-vision) or something similar.

**Comment by djohnsonnz** [comment]
The reason I want this is to accurately provide the lighting condition the token in question sees its surroundings.

Creatures with darkvision perceive dim light as bright light and darkness as dim light I want to set an active effect on the dark and dim effects to emulate these conditions (disadvantage on perception checks for dim light, blindness for dark). As it is if I set these effects creatures with darkvision will not get the correct effect applied.

**Comment by Frstrm** [comment]
You may want to look at [Stealthy](https://github.com/Eligarf/stealthy) module.  I believe it handles perception checks based on token conditions as your saying, and does work with this module in regards to the effects being placed on tokens.
