### ISSUE TITLE
Bug: When updating a lot of tokens on a scene, a token gets 3 Dark/Dim icons

### ISSUE THREAD

**Issue by apoapostolov** [Frstrm/TokenLightCondition#43]
When entering a scene that needs to recalculate dark/dim status, some icons get 3 effects instead of 1.

**Comment by Frstrm** [comment]
Does it clear up, or persist?  and only when activating/switching scenes?

**Comment by apoapostolov** [comment]
I had issues replicating this on existing scenes where states are already set, so I ran it through some old scenes to get it to happen. It happens but rarely, and to only a few tokens. They clear up upon scene change, so this is just a visual problem. Probably not worthy to investigate further. Also seems to happen only when a scene has no states and states are applied to all tokens so it must be some racing conflict.

**Comment by Frstrm** [comment]
I'll keep an eye out for it, and reopen this if you get a solid repro.  Thanks.
