### ISSUE TITLE
Enhancement Request: Chat Verbosity Setting

### ISSUE THREAD

**Issue by neostryder** [Frstrm/TokenLightCondition#44]
Frstrm, I love your module!  Is there a chance you can add a setting option to control the verbosity of the chat output?  I personally would set it to silent, and just let the active effect indicators tell me what I need to know.  As simple as that.  I poked through your code and think I see how to do it, but thought I would run it by you and formally request this feature.  Thank you so much!

**Comment by Frstrm** [comment]
The module itself doesn't generate chat messages... outside of posting to the console, which are gated by a config setting.
I suspect you have another mod that is pinging to chat on effect changes... 
an example:
![image](https://user-images.githubusercontent.com/46358673/228965852-be204e56-a9e7-49b3-a8be-28f097960971.png)
However i'm not sure you can gate which effects get shown vs not.

If you can post a screen shot of the chat your seeing, I might be able to pin that down...

**Comment by neostryder** [comment]
Yes, I did some testing and this does solve the problem of the chat SPAM.  Thank you!
