### ISSUE TITLE
Enhancement Request: No Bouncing Text on Tokens on Transition

### ISSUE THREAD

**Issue by neostryder** [Frstrm/TokenLightCondition#45]
Hi, me again.  I wanted to keep the requests separate for convenience in development, but this one is similar.  I was wondering if you know how to disable the popping text that shows every time a token's light level transitions, and can give us a setting to turn that off in favor of just seeing the active effect badges on the tokens.  I do use this module: [RPG Damage Numbers](https://theripper93.com/module/damage-numbers), and they do interact, but if I'm not mistaken, this is a core functionality of Foundry and would display even without that module installed.  I don't want to turn off the bouncing text for everything, as I like having it for damage, but it's a bit much when everyone is moving around at once with torches, or in and out of lights, and the screen is just blasted with multiple animated text messages on every step.  I think having the option to turn them off would be a great enhancement for your module.  Thank you!

**Comment by Frstrm** [comment]
I believe what your looking for unfortunately is part of the core settings:
![image](https://user-images.githubusercontent.com/46358673/228967708-b3561edf-16fe-44b0-874c-cc272442fa3e.png)

And it looks like this might be all or nothing.

Something I could look at, is maybe a setting where it's only processing effects during combat or some other associated option.  There is a option I added to the light controls, but that disables or enables vs suspends effect changes.

**Comment by neostryder** [comment]
Yes, I have inquired in the Foundry Discord for any suggestions, but for now, I will have to do without my scrolling text, as I want your darkness effects more than I want the RPG-like damage numbers.  Thank you!
