### ISSUE TITLE
[Feature request] Active Effect adjustment

### ISSUE THREAD

**Issue by maxobremer** [Frstrm/TokenLightCondition#46]
It would be nice if you could adjust the active effects for the different light conditions. 
For example it would be nice if the effect might not be visible on tokens, but have the effect adjust the opacity of a token for example or any other effect that a gm might want to give to a character such as disadvantage on perception checks via midi flags or something like that,.
that way gives some freedom to dm's to use this a bit more freeform

**Comment by Frstrm** [comment]
The ability to have the light conditions apply other effects or conditions is outside the scope of this module.
If you use CE, or CUB, the effects being applied are stored in those systems, which allow you to modify those effects directly to add additional functions.  i.e. if you want to apply those additional flags, or things like ATL settings.
There is a mode that doesn't add effects, but allows you to see the condition just from the Token Hud.  And those values are stored in the flags of the actor/token, so other modules/system could be driven off those settings.
