### ISSUE TITLE
PF2e: does not account for global illumination

### ISSUE THREAD

**Issue by HenriDeh** [Frstrm/TokenLightCondition#47]
TLC seems to be incompatible with rule-based vision of the PF2e system. In a scene transitioned to daylight (and thus to global illumination, the tokens keep their dark status. This is not solved by removing or reapplying. TLC seems to think that they are still in the dark. Only bright light from light sources can remove the condition it seems.

**Comment by Frstrm** [comment]
Can you verify for me if you have the global illumination option enabled in the Token Light Condition settings for me?
![image](https://user-images.githubusercontent.com/46358673/231615740-807d8859-dc7e-4b77-a4b2-508eedec020c.png)

**Comment by HenriDeh** [comment]
Oh weird, I'm pretty sure I had it checked when I investigated. But it wasn't, now it works. Sorry for the trouble.
