### ISSUE TITLE
[V11] TLC 0.6.1 and PF2 5.0.1 - no light conditions appear at all

### ISSUE THREAD

**Issue by apoapostolov** [Frstrm/TokenLightCondition#51]
On a scene where I had always had conditions due to lack of light, conditions disappeared on an update to 0.6.1 and no movement away from light assigns them.

**Comment by Frstrm** [comment]
Possible fix with 0.6.2
Issue: Config change caused effects to not be applied to tokens due to a check against ATL not updated for pf2e system.

This is a temporary fix.

TODO: allow config option that is not dependent on an outside module to allow pf2e system to post effects to token

**Comment by Frstrm** [comment]
0.6.3
Restores token light condition effects option to pf2e system

**Comment by apoapostolov** [comment]
Thank you. Will check in a few.
