### ISSUE TITLE
[V11] Massive slowdowns / choppiness of movement in PF2E

### ISSUE THREAD

**Issue by apoapostolov** [Frstrm/TokenLightCondition#52]
With TokenLightCondition on, the movement of tokens is prolonged and choppy, with no fluid animations, and appears at the end of movement points (with Drag Ruler, changes of movement vectors). The issue only happens with the mod. It must be something related to the optimization of calculation during movement.

**Comment by apoapostolov** [comment]
This may be resolved if there is no light calculation during movement, only when a movement ends.

**Comment by Frstrm** [comment]
Updated with 0.6.4
This will probably be solved via use of the Delay Calculations.  You may have to adjust the delay based on range of token movement expected.
