### ISSUE TITLE
V11 CE Error when creating effects

### ISSUE THREAD

**Issue by txm3278** [Frstrm/TokenLightCondition#54]
On launch, the necessary effects fail to create which causes the canvas to crash

![image](https://github.com/Frstrm/TokenLightCondition/assets/25332081/01bd576b-e096-4775-8826-8764ef3a7c81)

**Comment by Frstrm** [comment]
I have been unable to repro with latest builds, and believe this is no longer occurring.  Please reopen if that is not correct.
