### ISSUE TITLE
[Feature request]: Allow to not show the application of the light condition

### ISSUE THREAD

**Issue by TrofimSelbs** [Frstrm/TokenLightCondition#63]
Hey, thank you for your module! I use it in tandem with Stealthy, and was wondering if there is a way to not show the "dim"/"dark" condition on token, but still have it working for other modules? I run a game that is always in the dark, so my players always see these badges. If there is already an option to change that - please let me know, as I haven't found it. Thank you in advance!

**Comment by Frstrm** [comment]
Are you referring to the 'effect' being placed on the token or the token hud element showing the 'BRT/DIM/DRK' status?

If you set the 'Source for lighting effect' to 'Disable token effect (None)', then the effect is no longer placed on the token, but the token hud element will still show the current state of the token ( and that state can still be used by other modules ).

**Comment by TrofimSelbs** [comment]
I assumed that disabling "Source for lighting effect" would break something. Thank you, this fixes my issue!
