### ISSUE TITLE
Lagging severely when in use

### ISSUE THREAD

**Issue by demotech89** [Frstrm/TokenLightCondition#64]
I used find the culprit and determined that this module causes severe lag in the game when dragging tokens. I disabled it and all lag disappeared. I love this module so hopefully this might can get fixed in the future so that I can reinstall it again.

**Comment by demotech89** [comment]
In troubleshooting, raising the delay calucations seems to have helped tremendiously.

**Comment by Frstrm** [comment]
That is the expected way to deal with that issue.  unfortunately token update or refresh gets hit by at a high frequency.  I'll see if latest versions have increased this, but I was going to recommend using that delay option which you already found.
